### ISSUE TITLE
The delete article test is failing

### ISSUE THREAD

**Issue by qxf2** [qxf2/newsletter_automation#197]
Our automated test for delete article is failing. I am not sure why. Deleting articles on the application works just fine. Can a tester please fix this test?

Run: https://github.com/qxf2/newsletter_automation/actions/runs/3801534444/jobs/6466103381

**Comment by Archana-GS** [comment]
All tests are interdependent , removed -v and -k in the command , all tests are running fine now
https://github.com/qxf2/newsletter_automation/actions/runs/3828712061
https://github.com/qxf2/newsletter_automation/actions/runs/3828659223
https://github.com/qxf2/newsletter_automation/actions/runs/3828410194
